// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class Collection
{
    public int CollectionId { get; set; }

    public string CollectionName { get; set; }

    public int? CampaignId { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ICollection<CollectionProduct> CollectionProducts { get; set; } = new List<CollectionProduct>();
}