// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class CollectionProduct
{
    public int CollectionProductId { get; set; }

    public int? ProductId { get; set; }

    public int? CollectionId { get; set; }

    public virtual Collection Collection { get; set; }

    public virtual Product Product { get; set; }
}