// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Image { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public DateOnly? RegistrationDate { get; set; }

    public int? Otp { get; set; }

    public virtual ICollection<CustomerProduct> CustomerProducts { get; set; } = new List<CustomerProduct>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}