// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class CustomerProduct
{
    public int CustomerProductId { get; set; }

    public int? CustomerId { get; set; }

    public int? ProductId { get; set; }

    public DateOnly? BuyDate { get; set; }

    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Product Product { get; set; }
}