// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class OrderHistory
{
    public int LogId { get; set; }

    public int? OrderId { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public DateTime? ChangeTime { get; set; }

    public virtual Order Order { get; set; }
}