// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace F_LocalBrand.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? CategoryId { get; set; }

    public int? CampaignId { get; set; }

    public string SubCategory { get; set; }

    public string Gender { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public int? StockQuantity { get; set; }

    public string ImageUrl { get; set; }

    public int? Size { get; set; }

    public string Color { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<CollectionProduct> CollectionProducts { get; set; } = new List<CollectionProduct>();

    public virtual ICollection<Compapility> CompapilityProducts { get; set; } = new List<Compapility>();

    public virtual ICollection<Compapility> CompapilityRecommendedProducts { get; set; } = new List<Compapility>();

    public virtual ICollection<CustomerProduct> CustomerProducts { get; set; } = new List<CustomerProduct>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}